openapi: 3.0.1
info:
  title: CaffBackend
  version: '1.0'
paths:
  /api/Caff:
    post:
      tags:
        - Caff
      requestBody:
        content:
          multipart/form-data:
            schema:
              type: object
              properties:
                File:
                  type: string
                  format: binary
            encoding:
              File:
                style: form
      responses:
        '200':
          description: Success
    get:
      tags:
        - Caff
      responses:
        '200':
          description: Success
          content:
            text/plain:
              schema:
                type: array
                items:
                  $ref: '#/components/schemas/CaffResponse'
            application/json:
              schema:
                type: array
                items:
                  $ref: '#/components/schemas/CaffResponse'
            text/json:
              schema:
                type: array
                items:
                  $ref: '#/components/schemas/CaffResponse'
  /api/Caff/{id}:
    get:
      tags:
        - Caff
      parameters:
        - name: id
          in: path
          required: true
          schema:
            type: integer
            format: int32
      responses:
        '200':
          description: Success
    delete:
      tags:
        - Caff
      parameters:
        - name: id
          in: path
          required: true
          schema:
            type: integer
            format: int32
      responses:
        '200':
          description: Success
  /api/Caff/{id}/preview:
    get:
      tags:
        - Caff
      parameters:
        - name: id
          in: path
          required: true
          schema:
            type: integer
            format: int32
      responses:
        '200':
          description: Success
  /api/caff/{id}/comment:
    post:
      tags:
        - CaffComment
      parameters:
        - name: id
          in: path
          required: true
          schema:
            type: integer
            format: int32
      requestBody:
        content:
          application/json:
            schema:
              type: string
          text/json:
            schema:
              type: string
          application/*+json:
            schema:
              type: string
      responses:
        '200':
          description: Success
    get:
      tags:
        - CaffComment
      parameters:
        - name: id
          in: path
          required: true
          schema:
            type: integer
            format: int32
      responses:
        '200':
          description: Success
          content:
            text/plain:
              schema:
                type: array
                items:
                  $ref: '#/components/schemas/CaffCommentResponse'
            application/json:
              schema:
                type: array
                items:
                  $ref: '#/components/schemas/CaffCommentResponse'
            text/json:
              schema:
                type: array
                items:
                  $ref: '#/components/schemas/CaffCommentResponse'
  /api/caff/{id}/comment/{commentId}:
    delete:
      tags:
        - CaffComment
      parameters:
        - name: id
          in: path
          required: true
          schema:
            type: integer
            format: int32
        - name: commentId
          in: path
          required: true
          schema:
            type: integer
            format: int32
      responses:
        '200':
          description: Success
  /api/User/register:
    post:
      tags:
        - User
      requestBody:
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/RegisterRequest'
          text/json:
            schema:
              $ref: '#/components/schemas/RegisterRequest'
          application/*+json:
            schema:
              $ref: '#/components/schemas/RegisterRequest'
      responses:
        '200':
          description: Success
  /api/User/login:
    post:
      tags:
        - User
      requestBody:
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/LoginRequest'
          text/json:
            schema:
              $ref: '#/components/schemas/LoginRequest'
          application/*+json:
            schema:
              $ref: '#/components/schemas/LoginRequest'
      responses:
        '200':
          description: Success
  /api/User/make-admin:
    post:
      tags:
        - User
      requestBody:
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/MakeAdminRequest'
          text/json:
            schema:
              $ref: '#/components/schemas/MakeAdminRequest'
          application/*+json:
            schema:
              $ref: '#/components/schemas/MakeAdminRequest'
      responses:
        '200':
          description: Success
  /api/User/{id}:
    delete:
      tags:
        - User
      parameters:
        - name: id
          in: path
          required: true
          schema:
            type: string
      responses:
        '200':
          description: Success
  /api/User:
    get:
      tags:
        - User
      responses:
        '200':
          description: Success
          content:
            text/plain:
              schema:
                type: array
                items:
                  $ref: '#/components/schemas/UserResponse'
            application/json:
              schema:
                type: array
                items:
                  $ref: '#/components/schemas/UserResponse'
            text/json:
              schema:
                type: array
                items:
                  $ref: '#/components/schemas/UserResponse'
components:
  schemas:
    CaffCommentResponse:
      type: object
      properties:
        id:
          type: integer
          format: int32
        comment:
          type: string
          nullable: true
        userName:
          type: string
          nullable: true
      additionalProperties: false
    CaffResponse:
      type: object
      properties:
        id:
          type: integer
          format: int32
        tags:
          type: array
          items:
            type: string
          nullable: true
        fileName:
          type: string
          nullable: true
      additionalProperties: false
    LoginRequest:
      type: object
      properties:
        userName:
          type: string
          nullable: true
        password:
          type: string
          nullable: true
      additionalProperties: false
    MakeAdminRequest:
      type: object
      properties:
        userId:
          type: string
          nullable: true
      additionalProperties: false
    RegisterRequest:
      type: object
      properties:
        userName:
          type: string
          nullable: true
        password:
          type: string
          nullable: true
        email:
          type: string
          nullable: true
      additionalProperties: false
    UserResponse:
      type: object
      properties:
        id:
          type: string
          nullable: true
        userName:
          type: string
          nullable: true
        email:
          type: string
          nullable: true
      additionalProperties: false
